USE [master]
GO

/****** Object:  Database [TestMCF]    Script Date: 17/01/2024 21:53:04 ******/
CREATE DATABASE [TestMCF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestMCF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TestMCF.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestMCF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TestMCF_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestMCF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestMCF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestMCF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestMCF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestMCF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestMCF] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestMCF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TestMCF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestMCF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestMCF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestMCF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestMCF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestMCF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestMCF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestMCF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestMCF] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TestMCF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestMCF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestMCF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestMCF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestMCF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestMCF] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TestMCF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestMCF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestMCF] SET  MULTI_USER 
GO

ALTER DATABASE [TestMCF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestMCF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestMCF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestMCF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestMCF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestMCF] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TestMCF] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestMCF] SET  READ_WRITE 
GO


